// Generated by gencpp from file object_detect/cylinderdataResponse.msg
// DO NOT EDIT!


#ifndef OBJECT_DETECT_MESSAGE_CYLINDERDATARESPONSE_H
#define OBJECT_DETECT_MESSAGE_CYLINDERDATARESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace object_detect
{
template <class ContainerAllocator>
struct cylinderdataResponse_
{
  typedef cylinderdataResponse_<ContainerAllocator> Type;

  cylinderdataResponse_()
    : x(0.0)
    , z(0.0)
    , theta(0.0)
    , has_cylinder(false)  {
    }
  cylinderdataResponse_(const ContainerAllocator& _alloc)
    : x(0.0)
    , z(0.0)
    , theta(0.0)
    , has_cylinder(false)  {
    }



   typedef double _x_type;
  _x_type x;

   typedef double _z_type;
  _z_type z;

   typedef double _theta_type;
  _theta_type theta;

   typedef uint8_t _has_cylinder_type;
  _has_cylinder_type has_cylinder;




  typedef boost::shared_ptr< ::object_detect::cylinderdataResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_detect::cylinderdataResponse_<ContainerAllocator> const> ConstPtr;

}; // struct cylinderdataResponse_

typedef ::object_detect::cylinderdataResponse_<std::allocator<void> > cylinderdataResponse;

typedef boost::shared_ptr< ::object_detect::cylinderdataResponse > cylinderdataResponsePtr;
typedef boost::shared_ptr< ::object_detect::cylinderdataResponse const> cylinderdataResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_detect::cylinderdataResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_detect::cylinderdataResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace object_detect

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::object_detect::cylinderdataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_detect::cylinderdataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detect::cylinderdataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detect::cylinderdataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detect::cylinderdataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detect::cylinderdataResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_detect::cylinderdataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e041cb920e14ae2da5c3205d03cec266";
  }

  static const char* value(const ::object_detect::cylinderdataResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe041cb920e14ae2dULL;
  static const uint64_t static_value2 = 0xa5c3205d03cec266ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_detect::cylinderdataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_detect/cylinderdataResponse";
  }

  static const char* value(const ::object_detect::cylinderdataResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_detect::cylinderdataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 z\n\
float64 theta\n\
bool has_cylinder\n\
\n\
";
  }

  static const char* value(const ::object_detect::cylinderdataResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_detect::cylinderdataResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.z);
      stream.next(m.theta);
      stream.next(m.has_cylinder);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct cylinderdataResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_detect::cylinderdataResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_detect::cylinderdataResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
    s << indent << "has_cylinder: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.has_cylinder);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_DETECT_MESSAGE_CYLINDERDATARESPONSE_H
