// Generated by gencpp from file object_detect/cylinderdata.msg
// DO NOT EDIT!


#ifndef OBJECT_DETECT_MESSAGE_CYLINDERDATA_H
#define OBJECT_DETECT_MESSAGE_CYLINDERDATA_H

#include <ros/service_traits.h>


#include <object_detect/cylinderdataRequest.h>
#include <object_detect/cylinderdataResponse.h>


namespace object_detect
{

struct cylinderdata
{

typedef cylinderdataRequest Request;
typedef cylinderdataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cylinderdata
} // namespace object_detect


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::object_detect::cylinderdata > {
  static const char* value()
  {
    return "b9e8980f8b8e3ef5fefd96c05b856874";
  }

  static const char* value(const ::object_detect::cylinderdata&) { return value(); }
};

template<>
struct DataType< ::object_detect::cylinderdata > {
  static const char* value()
  {
    return "object_detect/cylinderdata";
  }

  static const char* value(const ::object_detect::cylinderdata&) { return value(); }
};


// service_traits::MD5Sum< ::object_detect::cylinderdataRequest> should match 
// service_traits::MD5Sum< ::object_detect::cylinderdata > 
template<>
struct MD5Sum< ::object_detect::cylinderdataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::object_detect::cylinderdata >::value();
  }
  static const char* value(const ::object_detect::cylinderdataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_detect::cylinderdataRequest> should match 
// service_traits::DataType< ::object_detect::cylinderdata > 
template<>
struct DataType< ::object_detect::cylinderdataRequest>
{
  static const char* value()
  {
    return DataType< ::object_detect::cylinderdata >::value();
  }
  static const char* value(const ::object_detect::cylinderdataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::object_detect::cylinderdataResponse> should match 
// service_traits::MD5Sum< ::object_detect::cylinderdata > 
template<>
struct MD5Sum< ::object_detect::cylinderdataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::object_detect::cylinderdata >::value();
  }
  static const char* value(const ::object_detect::cylinderdataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_detect::cylinderdataResponse> should match 
// service_traits::DataType< ::object_detect::cylinderdata > 
template<>
struct DataType< ::object_detect::cylinderdataResponse>
{
  static const char* value()
  {
    return DataType< ::object_detect::cylinderdata >::value();
  }
  static const char* value(const ::object_detect::cylinderdataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OBJECT_DETECT_MESSAGE_CYLINDERDATA_H
