// Generated by gencpp from file object_detect/volleyballdataRequest.msg
// DO NOT EDIT!


#ifndef OBJECT_DETECT_MESSAGE_VOLLEYBALLDATAREQUEST_H
#define OBJECT_DETECT_MESSAGE_VOLLEYBALLDATAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace object_detect
{
template <class ContainerAllocator>
struct volleyballdataRequest_
{
  typedef volleyballdataRequest_<ContainerAllocator> Type;

  volleyballdataRequest_()
    : ball_or_cylinder(false)  {
    }
  volleyballdataRequest_(const ContainerAllocator& _alloc)
    : ball_or_cylinder(false)  {
    }



   typedef uint8_t _ball_or_cylinder_type;
  _ball_or_cylinder_type ball_or_cylinder;




  typedef boost::shared_ptr< ::object_detect::volleyballdataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_detect::volleyballdataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct volleyballdataRequest_

typedef ::object_detect::volleyballdataRequest_<std::allocator<void> > volleyballdataRequest;

typedef boost::shared_ptr< ::object_detect::volleyballdataRequest > volleyballdataRequestPtr;
typedef boost::shared_ptr< ::object_detect::volleyballdataRequest const> volleyballdataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_detect::volleyballdataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_detect::volleyballdataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace object_detect

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::object_detect::volleyballdataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_detect::volleyballdataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detect::volleyballdataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detect::volleyballdataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detect::volleyballdataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detect::volleyballdataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_detect::volleyballdataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "05d1068bf0059d7ff7e653ac02810247";
  }

  static const char* value(const ::object_detect::volleyballdataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x05d1068bf0059d7fULL;
  static const uint64_t static_value2 = 0xf7e653ac02810247ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_detect::volleyballdataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_detect/volleyballdataRequest";
  }

  static const char* value(const ::object_detect::volleyballdataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_detect::volleyballdataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ball_or_cylinder\n\
";
  }

  static const char* value(const ::object_detect::volleyballdataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_detect::volleyballdataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ball_or_cylinder);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct volleyballdataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_detect::volleyballdataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_detect::volleyballdataRequest_<ContainerAllocator>& v)
  {
    s << indent << "ball_or_cylinder: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ball_or_cylinder);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_DETECT_MESSAGE_VOLLEYBALLDATAREQUEST_H
