// Generated by gencpp from file object_detect/volleyballdataResponse.msg
// DO NOT EDIT!


#ifndef OBJECT_DETECT_MESSAGE_VOLLEYBALLDATARESPONSE_H
#define OBJECT_DETECT_MESSAGE_VOLLEYBALLDATARESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace object_detect
{
template <class ContainerAllocator>
struct volleyballdataResponse_
{
  typedef volleyballdataResponse_<ContainerAllocator> Type;

  volleyballdataResponse_()
    : has_ball(false)
    , if_volleyball(false)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , theta(0.0)  {
    }
  volleyballdataResponse_(const ContainerAllocator& _alloc)
    : has_ball(false)
    , if_volleyball(false)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , theta(0.0)  {
    }



   typedef uint8_t _has_ball_type;
  _has_ball_type has_ball;

   typedef uint8_t _if_volleyball_type;
  _if_volleyball_type if_volleyball;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _theta_type;
  _theta_type theta;




  typedef boost::shared_ptr< ::object_detect::volleyballdataResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_detect::volleyballdataResponse_<ContainerAllocator> const> ConstPtr;

}; // struct volleyballdataResponse_

typedef ::object_detect::volleyballdataResponse_<std::allocator<void> > volleyballdataResponse;

typedef boost::shared_ptr< ::object_detect::volleyballdataResponse > volleyballdataResponsePtr;
typedef boost::shared_ptr< ::object_detect::volleyballdataResponse const> volleyballdataResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_detect::volleyballdataResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_detect::volleyballdataResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace object_detect

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::object_detect::volleyballdataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_detect::volleyballdataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detect::volleyballdataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detect::volleyballdataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detect::volleyballdataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detect::volleyballdataResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_detect::volleyballdataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d71b46a34dd3d2b473eaed28c25a28ee";
  }

  static const char* value(const ::object_detect::volleyballdataResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd71b46a34dd3d2b4ULL;
  static const uint64_t static_value2 = 0x73eaed28c25a28eeULL;
};

template<class ContainerAllocator>
struct DataType< ::object_detect::volleyballdataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_detect/volleyballdataResponse";
  }

  static const char* value(const ::object_detect::volleyballdataResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_detect::volleyballdataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool has_ball\n\
bool if_volleyball\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 theta\n\
\n\
";
  }

  static const char* value(const ::object_detect::volleyballdataResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_detect::volleyballdataResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.has_ball);
      stream.next(m.if_volleyball);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct volleyballdataResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_detect::volleyballdataResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_detect::volleyballdataResponse_<ContainerAllocator>& v)
  {
    s << indent << "has_ball: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.has_ball);
    s << indent << "if_volleyball: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.if_volleyball);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_DETECT_MESSAGE_VOLLEYBALLDATARESPONSE_H
